version: '2'
services:
    mobot:
        build: .
        volumes:
            - .:/mobot
        depends_on:
            - redis_db
    redis_db:
        image: "redis:alpine"
        command: redis-server --appendonly yes
        volumes:
            - ./data:/data
